# NUMPY - 1 - Assignment 

##    By Prakash Ghosh
------

### Problem 1. Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

def Vandermonde(vector,N):    
    Matrix_Ouptput = np.column_stack([vector**(N-i-1) for i in range(N)])      
    return Matrix_Ouptput

# Call Vandermonde with a vector and order      
lstInput=np.array(range(7))
print(Vandermonde(lstInput,8))


[[     0      0      0      0      0      0      0      1]
 [     1      1      1      1      1      1      1      1]
 [   128     64     32     16      8      4      2      1]
 [  2187    729    243     81     27      9      3      1]
 [ 16384   4096   1024    256     64     16      4      1]
 [ 78125  15625   3125    625    125     25      5      1]
 [279936  46656   7776   1296    216     36      6      1]]
